version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: docker-roombook
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - redis

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: docker-redis
    ports:
      - "6379:6379"
